CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.dashboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL UNIQUE,
  content TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public read posts" ON public.posts;
CREATE POLICY "public read posts"
ON public.posts FOR SELECT TO anon
USING (true);

DROP POLICY IF EXISTS "public read dashboard" ON public.dashboard;
CREATE POLICY "public read dashboard"
ON public.dashboard FOR SELECT TO anon
USING (true);

INSERT INTO public.dashboard (title, content) VALUES
  ('Gold', NULL),
  ('Silver', NULL),
  ('Platinum', NULL),
  ('Copper', NULL),
  ('Neodymium', NULL),
  ('Uranium', NULL),
  ('S&P 500', NULL),
  ('Nasdaq Composite', NULL),
  ('Dow Jones Industrial Average', NULL),
  ('DAX', NULL),
  ('Nikkei 225', NULL),
  ('Hang Seng Index', NULL),
  ('BTC/USD', NULL),
  ('US 10Y Bond', NULL)
ON CONFLICT (title) DO NOTHING;
