version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/services/article-extractor"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "npm"
    directory: "/services/storage-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
